### PR TITLE
Add JUnit tests for Quadrilateral shape

### PR DESCRIPTION
**Pull request by KevinDzj**
## What is the type of change?
  - [x] Bug Fix
  - [x] New Feature
  - [x] New Test Cases
  - [x] Documentation Update

## Complete the following before creating a pull request:
  - [x] I have performed a self code review
  - [x] I have tested changes locally
  - [x] I have documented the new changes

### CODE REVIEW

**Comment by KevinDzj** [comment]
+package lab4;
+
+public class Quadrilateral {
+
+       Point A;
+       Point B;
+       Point C;
+       Point D;
+
+       public Quadrilateral(Point A, Point B, Point C, Point D) {
+
+               // assumes user inputs points in clockwise or counterclockwise order of a valid Quadrilateral
+
+               this.A = A;
+               this.B = B;
+               this.C = C;
+               this.D = D;
+       }
+
+       public double perimeter() {
+               return A.distance(B) + B.distance(C) + C.distance(D) + D.distance(A);
+       }
+

**Comment by Preston018** [comment]
diff --git a/QuadrilateralTests.java b/QuadrilateralTests.java
new file mode 100644
index 0000000..bbddf24
--- /dev/null
+++ b/QuadrilateralTests.java
@@ -0,0 +1,39 @@
+package lab4;
+
+import static org.junit.jupiter.api.Assertions.*;
+
+import org.junit.jupiter.api.Test;
+
+class QuadrilateralTests {
+
+       @Test
+       void testPerimeter() {
+               Point p1 = new Point(0.0, 0.0);
+               Point p2 = new Point(0.0, 1.0);
+               Point p3 = new Point(2.0, 1.0);
+               Point p4 = new Point(2.0, 0.0);
+               Quadrilateral q1 = new Quadrilateral(p1, p2, p3, p4);
+               assertEquals(q1.perimeter(), 6.0);
+       }
+       
+       @Test
+       void testTriangleArea() {
+               Point p1 = new Point(0.0, 0.0);
+               Point p2 = new Point(0.0, 1.0);
+               Point p3 = new Point(2.0, 1.0);
+               Point p4 = new Point(2.0, 0.0);
+               Quadrilateral q1 = new Quadrilateral(p1, p2, p3, p4);
+               assertEquals(q1.triangleArea(p1, p2, p3), 1.0);
+       }
+       
+       @Test
+       void testArea() {
+               Point p1 = new Point(0.0, 0.0);
+               Point p2 = new Point(0.0, 1.0);
+               Point p3 = new Point(2.0, 1.0);
+               Point p4 = new Point(2.0, 0.0);
+               Quadrilateral q1 = new Quadrilateral(p1, p2, p3, p4);
+               assertEquals(q1.area(), 2.0);
+       }
+
+}
(END)

**Comment by KevinDzj** [comment]
diff --git a/Quadrilateral.java b/Quadrilateral.java
new file mode 100644
index 0000000..7a97826
--- /dev/null
+++ b/Quadrilateral.java
@@ -0,0 +1,39 @@
+package lab4;
+
+public class Quadrilateral {
+
+       Point A;
+       Point B;
+       Point C;
+       Point D;
+
+       public Quadrilateral(Point A, Point B, Point C, Point D) {
+
+               // assumes user inputs points in clockwise or counterclockwise order of a valid Quadrilateral
+
+               this.A = A;
+               this.B = B;
+               this.C = C;
+               this.D = D;
+       }
+
+       public double perimeter() {
+               return A.distance(B) + B.distance(C) + C.distance(D) + D.distance(A);
+       }
+

**Comment by KevinDzj** [comment]
diff --git a/Quadrilateral.java b/Quadrilateral.java
new file mode 100644
index 0000000..7a97826
--- /dev/null
+++ b/Quadrilateral.java
@@ -0,0 +1,39 @@
+package lab4;
+
+public class Quadrilateral {
+
+       Point A;
+       Point B;
+       Point C;
+       Point D;
+
+       public Quadrilateral(Point A, Point B, Point C, Point D) {
+
+               // assumes user inputs points in clockwise or counterclockwise order of a valid Quadrilateral
+
+               this.A = A;
+               this.B = B;
+               this.C = C;
+               this.D = D;
+       }
+
+       public double perimeter() {
+               return A.distance(B) + B.distance(C) + C.distance(D) + D.distance(A);
+       }
+
+       public double area() {
+               return triangleArea(A, B, C) + triangleArea(A, D, C); // two halves of the quad
+       }
+
+       public double triangleArea(Point A, Point B, Point C) {
+
+               double semiP = 0, area = 0;
+
+               semiP = (A.distance(B) + B.distance(C) + C.distance(A)) / 2;
+
+               area = Math.sqrt(semiP * (semiP - A.distance(B)) *
+                               (semiP - B.distance(C)) * (semiP - C.distance(A)));
+
+               return area;
+       }
+}

**Pull request merged**
